package com.google.android.gms.internal.ads;

import android.content.Context;
import android.content.SharedPreferences;
import androidx.exifinterface.media.ExifInterface;
import androidx.recyclerview.widget.ItemTouchHelper;
import androidx.room.RoomDatabase;
import com.amplitude.api.Constants;
import com.facebook.react.uimanager.ViewProps;
import com.google.android.exoplayer2.DefaultRenderersFactory;
import com.google.android.exoplayer2.trackselection.AdaptiveTrackSelection;
import java.util.List;
import java.util.concurrent.TimeUnit;
import org.apache.commons.lang3.time.DateUtils;
import org.json.JSONObject;

@zzard
public final class zzacu {
    private static final zzacj<String> zzckt = zzacj.zzb(0, "gads:sdk_core_experiment_id");
    public static final zzacj<String> zzcku = zzacj.zza(0, "gads:sdk_core_location", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/sdk-core-v40-loader.html");
    public static final zzacj<String> zzckv = zzacj.zza(1, "gads:sdk_core_location:client:html", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/sdk-core-v40-impl.html");
    public static final zzacj<String> zzckw = zzacj.zza(1, "gads:active_view_location:html", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/sdk-core-v40-impl.html");
    private static final zzacj<String> zzckx = zzacj.zza(0, "gads:sdk_core_js_location", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/sdk-core-v40-impl.js");
    private static final zzacj<Boolean> zzcky = zzacj.zza(0, "gads:request_builder:singleton_webview", (Boolean) false);
    private static final zzacj<String> zzckz = zzacj.zzb(0, "gads:request_builder:singleton_webview_experiment_id");
    private static final zzacj<String> zzcla = zzacj.zzb(0, "gads:request_builder:refresh_if_destroyed:experiment_id");
    public static final zzacj<Boolean> zzclb = zzacj.zza(0, "gads:request_builder:refresh_if_destroyed:enable", (Boolean) true);
    private static final zzacj<Boolean> zzclc = zzacj.zza(0, "gads:sdk_use_dynamic_module", (Boolean) true);
    private static final zzacj<String> zzcld = zzacj.zzb(0, "gads:sdk_use_dynamic_module_experiment_id");
    public static final zzacj<Boolean> zzcle = zzacj.zza(0, "gads:sdk_crash_report_enabled", (Boolean) false);
    public static final zzacj<Boolean> zzclf = zzacj.zza(0, "gads:report_dynamite_crash_in_background_thread", (Boolean) false);
    public static final zzacj<Boolean> zzclg = zzacj.zza(0, "gads:sdk_crash_report_full_stacktrace", (Boolean) false);
    public static final zzacj<String> zzclh = zzacj.zza(0, "gads:sdk_crash_report_class_prefix", "com.google.");
    public static final zzacj<Float> zzcli = zzacj.zza(1, "gads:trapped_exception_sample_rate", 0.01f);
    private static final zzacj<String> zzclj = zzacj.zzb(0, "gads:block_autoclicks_experiment_id");
    private static final zzacj<String> zzclk = zzacj.zzb(0, "gads:spam_app_context:experiment_id");
    private static final zzacj<Integer> zzcll = zzacj.zza(1, "gads:http_url_connection_factory:timeout_millis", 10000);
    public static final zzacj<String> zzclm = zzacj.zza(1, "gads:video_exo_player:version", ExifInterface.GPS_MEASUREMENT_3D);
    public static final zzacj<Integer> zzcln = zzacj.zza(1, "gads:video_exo_player:connect_timeout", 8000);
    public static final zzacj<Integer> zzclo = zzacj.zza(1, "gads:video_exo_player:read_timeout", 8000);
    public static final zzacj<Integer> zzclp = zzacj.zza(1, "gads:video_exo_player:loading_check_interval", 1048576);
    public static final zzacj<Integer> zzclq = zzacj.zza(1, "gads:video_exo_player:exo_player_precache_limit", Integer.MAX_VALUE);
    public static final zzacj<Integer> zzclr = zzacj.zza(1, "gads:video_exo_player:byte_buffer_precache_limit", Integer.MAX_VALUE);
    public static final zzacj<Integer> zzcls = zzacj.zza(1, "gads:video_exo_player_socket_receive_buffer_size", 0);
    private static final zzacj<String> zzclt = zzacj.zzb(0, "gads:video_stream_cache:experiment_id");
    public static final zzacj<Integer> zzclu = zzacj.zza(1, "gads:video_stream_cache:limit_count", 5);
    public static final zzacj<Integer> zzclv = zzacj.zza(1, "gads:video_stream_cache:limit_space", 8388608);
    public static final zzacj<Integer> zzclw = zzacj.zza(1, "gads:video_stream_exo_cache:buffer_size", 8388608);
    public static final zzacj<Long> zzclx = zzacj.zza(1, "gads:video_stream_cache:limit_time_sec", 300);
    public static final zzacj<Long> zzcly = zzacj.zza(1, "gads:video_stream_cache:notify_interval_millis", 125);
    public static final zzacj<Integer> zzclz = zzacj.zza(1, "gads:video_stream_cache:connect_timeout_millis", 10000);
    public static final zzacj<Boolean> zzcma = zzacj.zza(0, "gads:video:metric_reporting_enabled", (Boolean) false);
    public static final zzacj<String> zzcmb = zzacj.zza(1, "gads:video:metric_frame_hash_times", "");
    public static final zzacj<Long> zzcmc = zzacj.zza(1, "gads:video:metric_frame_hash_time_leniency", 500);
    public static final zzacj<Boolean> zzcmd = zzacj.zza(1, "gads:video:force_watermark", (Boolean) false);
    public static final zzacj<Long> zzcme = zzacj.zza(1, "gads:video:surface_update_min_spacing_ms", 1000);
    public static final zzacj<Boolean> zzcmf = zzacj.zza(1, "gads:video:spinner:enabled", (Boolean) false);
    public static final zzacj<Integer> zzcmg = zzacj.zza(1, "gads:video:spinner:scale", 4);
    public static final zzacj<Long> zzcmh = zzacj.zza(1, "gads:video:spinner:jank_threshold_ms", 50);
    public static final zzacj<Boolean> zzcmi = zzacj.zza(1, "gads:video:aggressive_media_codec_release", (Boolean) false);
    public static final zzacj<Boolean> zzcmj = zzacj.zza(1, "gads:memory_bundle:debug_info", (Boolean) false);
    public static final zzacj<String> zzcmk = zzacj.zza(1, "gads:video:codec_query_mime_types", "");
    public static final zzacj<Integer> zzcml = zzacj.zza(1, "gads:video:codec_query_minimum_version", 16);
    private static final zzacj<Float> zzcmm = zzacj.zza(0, "gads:ad_id_app_context:ping_ratio", 0.0f);
    private static final zzacj<String> zzcmn = zzacj.zzb(0, "gads:ad_id_use_shared_preference:experiment_id");
    private static final zzacj<Boolean> zzcmo = zzacj.zza(0, "gads:ad_id_use_shared_preference:enabled", (Boolean) false);
    private static final zzacj<Float> zzcmp = zzacj.zza(0, "gads:ad_id_use_shared_preference:ping_ratio", 0.0f);
    private static final zzacj<Boolean> zzcmq = zzacj.zza(0, "gads:ad_id_use_persistent_service:enabled", (Boolean) false);
    private static final zzacj<Boolean> zzcmr = zzacj.zza(0, "gads:ad_id:use_ipc:enabled", (Boolean) false);
    public static final zzacj<String> zzcms = zzacj.zza(1, "gad:mraid:url_banner", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_banner.js");
    public static final zzacj<String> zzcmt = zzacj.zza(1, "gad:mraid:url_expanded_banner", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_expanded_banner.js");
    public static final zzacj<String> zzcmu = zzacj.zza(1, "gad:mraid:url_interstitial", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_interstitial.js");
    public static final zzacj<String> zzcmv = zzacj.zza(1, "gad:mraid:version", "2.0");
    public static final zzacj<Boolean> zzcmw = zzacj.zza(1, "gads:mraid:unload", (Boolean) false);
    public static final zzacj<Boolean> zzcmx = zzacj.zza(0, "gads:enabled_sdk_csi", (Boolean) false);
    public static final zzacj<String> zzcmy = zzacj.zza(0, "gads:sdk_csi_server", "https://csi.gstatic.com/csi");
    public static final zzacj<Boolean> zzcmz = zzacj.zza(0, "gads:sdk_csi_write_to_file", (Boolean) false);
    public static final zzacj<Boolean> zzcna = zzacj.zza(0, "gads:enable_content_fetching", (Boolean) true);
    public static final zzacj<Integer> zzcnb = zzacj.zza(0, "gads:content_length_weight", 1);
    public static final zzacj<Integer> zzcnc = zzacj.zza(0, "gads:content_age_weight", 1);
    public static final zzacj<Integer> zzcnd = zzacj.zza(0, "gads:min_content_len", 11);
    public static final zzacj<Integer> zzcne = zzacj.zza(0, "gads:fingerprint_number", 10);
    public static final zzacj<Integer> zzcnf = zzacj.zza(0, "gads:sleep_sec", 10);
    public static final zzacj<Integer> zzcng = zzacj.zza(1, "gads:content_vertical_fingerprint_number", 100);
    public static final zzacj<Integer> zzcnh = zzacj.zza(1, "gads:content_vertical_fingerprint_bits", 23);
    public static final zzacj<Integer> zzcni = zzacj.zza(1, "gads:content_vertical_fingerprint_ngram", 3);
    public static final zzacj<String> zzcnj = zzacj.zza(1, "gads:content_fetch_view_tag_id", "googlebot");
    public static final zzacj<String> zzcnk = zzacj.zza(1, "gads:content_fetch_exclude_view_tag", ViewProps.NONE);
    public static final zzacj<Boolean> zzcnl = zzacj.zza(1, "gads:content_fetch_disable_get_title_from_webview", (Boolean) false);
    private static final zzacj<Boolean> zzcnm = zzacj.zza(0, "gads:app_index:without_content_info_present:enabled", (Boolean) true);
    private static final zzacj<Long> zzcnn = zzacj.zza(0, "gads:app_index:timeout_ms", 1000);
    private static final zzacj<String> zzcno = zzacj.zzb(0, "gads:app_index:experiment_id");
    public static final zzacj<Boolean> zzcnp = zzacj.zza(1, "gads:content_fetch_enable_new_content_score", (Boolean) false);
    public static final zzacj<Boolean> zzcnq = zzacj.zza(1, "gads:content_fetch_enable_serve_once", (Boolean) false);
    public static final zzacj<Boolean> zzcnr = zzacj.zza(0, "gads:ad_key_enabled", (Boolean) false);
    public static final zzacj<Boolean> zzcns = zzacj.zza(1, "gads:sai:enabled", (Boolean) true);
    public static final zzacj<String> zzcnt = zzacj.zza(1, "gads:sai:click_ping_schema_v2", "^[^?]*(/aclk\\?|/pcs/click\\?).*");
    public static final zzacj<String> zzcnu = zzacj.zza(1, "gads:sai:impression_ping_schema_v2", "^[^?]*/adview.*");
    public static final zzacj<Boolean> zzcnv = zzacj.zza(1, "gads:sai:using_macro:enabled", (Boolean) false);
    public static final zzacj<String> zzcnw = zzacj.zza(1, "gads:sai:ad_event_id_macro_name", "[gw_fbsaeid]");
    public static final zzacj<Long> zzcnx = zzacj.zza(1, "gads:sai:timeout_ms", -1);
    public static final zzacj<Integer> zzcny = zzacj.zza(1, "gads:sai:scion_thread_pool_size", 5);
    public static final zzacj<Boolean> zzcnz = zzacj.zza(1, "gads:sai:app_measurement_enabled2", (Boolean) false);
    public static final zzacj<Boolean> zzcoa = zzacj.zza(2, "app_measurement_enabled", (Boolean) false);
    public static final zzacj<Boolean> zzcob = zzacj.zza(1, "gads:sai:force_through_reflection", (Boolean) true);
    public static final zzacj<Boolean> zzcoc = zzacj.zza(1, "gads:sai:gmscore_availability_check_disabled", (Boolean) false);
    public static final zzacj<Boolean> zzcod = zzacj.zza(1, "gads:sai:logging_disabled_for_drx", (Boolean) false);
    public static final zzacj<Boolean> zzcoe = zzacj.zza(1, "gads:interstitial:app_must_be_foreground:enabled", (Boolean) false);
    public static final zzacj<Boolean> zzcof = zzacj.zza(1, "gads:interstitial:foreground_report:enabled", (Boolean) false);
    private static final zzacj<Integer> zzcog = zzacj.zza(0, "gads:webview_cache_version", 0);
    private static final zzacj<String> zzcoh = zzacj.zzb(0, "gads:corewebview:experiment_id");
    public static final zzacj<Boolean> zzcoi = zzacj.zza(0, "gads:corewebview:adwebview_factory:enable", (Boolean) false);
    public static final zzacj<Boolean> zzcoj = zzacj.zza(0, "gads:corewebview:javascript_engine", (Boolean) false);
    public static final zzacj<Boolean> zzcok = zzacj.zza(1, "gad:webview:inject_scripts", (Boolean) false);
    public static final zzacj<Boolean> zzcol = zzacj.zza(0, "gads:webview:permission:disabled", (Boolean) false);
    public static final zzacj<Boolean> zzcom = zzacj.zza(1, "gads:webview:error_web_response:enabled", (Boolean) false);
    private static final zzacj<Boolean> zzcon = zzacj.zza(1, "gads:rsku:webviewgone:kill_process:enabled", (Boolean) false);
    public static final zzacj<Boolean> zzcoo = zzacj.zza(1, "gads:webviewgone:kill_process:enabled", (Boolean) false);
    private static final zzacj<Boolean> zzcop = zzacj.zza(1, "gads:rsku:webviewgone:new_onshow:enabled", (Boolean) true);
    public static final zzacj<Boolean> zzcoq = zzacj.zza(1, "gads:webviewgone:new_onshow:enabled", (Boolean) false);
    private static final zzacj<String> zzcor = zzacj.zzc(0, "gads:pan:experiment_id");
    private static final zzacj<Boolean> zzcos = zzacj.zza(1, "gads:new_rewarded_ad:enabled", (Boolean) true);
    public static final zzacj<Boolean> zzcot = zzacj.zza(1, "gads:rewarded:adapter_initialization_enabled", (Boolean) false);
    private static final zzacj<Long> zzcou = zzacj.zza(1, "gads:rewarded:adapter_timeout_ms", 20000);
    public static final zzacj<Boolean> zzcov = zzacj.zza(1, "gads:rewarded:ad_metadata_enabled", (Boolean) false);
    public static final zzacj<Boolean> zzcow = zzacj.zza(1, "gads:rewarded:ssv_custom_data_enabled", (Boolean) true);
    public static final zzacj<Long> zzcox = zzacj.zza(1, "gads:app_activity_tracker:notify_background_listeners_delay_ms", 500);
    public static final zzacj<Long> zzcoy = zzacj.zza(1, "gads:app_activity_tracker:app_session_timeout_ms", TimeUnit.MINUTES.toMillis(5));
    public static final zzacj<Boolean> zzcoz = zzacj.zza(1, "gads:adid_values_in_adrequest:enabled", (Boolean) false);
    public static final zzacj<Long> zzcpa = zzacj.zza(1, "gads:adid_values_in_adrequest:timeout", (long) AdaptiveTrackSelection.DEFAULT_MIN_TIME_BETWEEN_BUFFER_REEVALUTATION_MS);
    public static final zzacj<Boolean> zzcpb = zzacj.zza(1, "gads:disable_adid_values_in_ms", (Boolean) false);
    private static final zzacj<Boolean> zzcpc = zzacj.zza(0, "gads:ad_serving:enabled", (Boolean) true);
    public static final zzacj<Long> zzcpd = zzacj.zza(1, "gads:ad_overlay:delay_page_close_timeout_ms", (long) DefaultRenderersFactory.DEFAULT_ALLOWED_VIDEO_JOINING_TIME_MS);
    public static final zzacj<Boolean> zzcpe = zzacj.zza(1, "gads:custom_close_blocking:enabled", (Boolean) false);
    public static final zzacj<Boolean> zzcpf = zzacj.zza(1, "gads:disabling_closable_area:enabled", (Boolean) false);
    public static final zzacj<Boolean> zzcpg = zzacj.zza(1, "gads:use_system_ui_for_fullscreen:enabled", (Boolean) false);
    public static final zzacj<Boolean> zzcph = zzacj.zza(1, "gads:ad_overlay:collect_cutout_info:enabled", (Boolean) false);
    private static final zzacj<Boolean> zzcpi = zzacj.zza(1, "gads:impression_optimization_enabled", (Boolean) false);
    private static final zzacj<String> zzcpj = zzacj.zza(1, "gads:banner_ad_pool:schema", "customTargeting");
    private static final zzacj<Integer> zzcpk = zzacj.zza(1, "gads:banner_ad_pool:max_queues", 3);
    private static final zzacj<Integer> zzcpl = zzacj.zza(1, "gads:banner_ad_pool:max_pools", 3);
    public static final zzacj<Boolean> zzcpm = zzacj.zza(1, "gads:delay_banner_renderer:enabled", (Boolean) true);
    private static final zzacj<Boolean> zzcpn = zzacj.zza(1, "gads:interstitial_ad_pool:enabled", (Boolean) false);
    private static final zzacj<Boolean> zzcpo = zzacj.zza(1, "gads:interstitial_ad_pool:enabled_for_rewarded", (Boolean) false);
    private static final zzacj<String> zzcpp = zzacj.zza(1, "gads:interstitial_ad_pool:schema", "customTargeting");
    private static final zzacj<String> zzcpq = zzacj.zza(1, "gads:interstitial_ad_pool:request_exclusions", "com.google.ads.mediation.admob.AdMobAdapter/_ad");
    private static final zzacj<Integer> zzcpr = zzacj.zza(1, "gads:interstitial_ad_pool:max_pools", 3);
    private static final zzacj<Integer> zzcps = zzacj.zza(1, "gads:interstitial_ad_pool:max_pool_depth", 2);
    private static final zzacj<Integer> zzcpt = zzacj.zza(1, "gads:interstitial_ad_pool:time_limit_sec", 1200);
    private static final zzacj<String> zzcpu = zzacj.zza(1, "gads:interstitial_ad_pool:ad_unit_exclusions", "(?!)");
    private static final zzacj<Integer> zzcpv = zzacj.zza(1, "gads:interstitial_ad_pool:top_off_latency_min_millis", 0);
    private static final zzacj<Integer> zzcpw = zzacj.zza(1, "gads:interstitial_ad_pool:top_off_latency_range_millis", 0);
    private static final zzacj<Long> zzcpx = zzacj.zza(1, "gads:interstitial_ad_pool:discard_thresholds", 0);
    private static final zzacj<Long> zzcpy = zzacj.zza(1, "gads:interstitial_ad_pool:miss_thresholds", 0);
    private static final zzacj<Float> zzcpz = zzacj.zza(1, "gads:interstitial_ad_pool:discard_asymptote", 0.0f);
    private static final zzacj<Float> zzcqa = zzacj.zza(1, "gads:interstitial_ad_pool:miss_asymptote", 0.0f);
    public static final zzacj<Boolean> zzcqb = zzacj.zza(0, "gads:debug_logging_feature:enable", (Boolean) false);
    public static final zzacj<Boolean> zzcqc = zzacj.zza(0, "gads:debug_logging_feature:intercept_web_view", (Boolean) false);
    private static final zzacj<Integer> zzcqd = zzacj.zza(1, "gads:heap_wastage:bytes", 0);
    public static final zzacj<String> zzcqe = zzacj.zza(1, "gads:spherical_video:vertex_shader", "");
    public static final zzacj<String> zzcqf = zzacj.zza(1, "gads:spherical_video:fragment_shader", "");
    public static final zzacj<Boolean> zzcqg = zzacj.zza(0, "gads:log:verbose_enabled", (Boolean) false);
    public static final zzacj<Boolean> zzcqh = zzacj.zza(1, "gads:include_local_global_rectangles", (Boolean) false);
    public static final zzacj<Long> zzcqi = zzacj.zza(1, "gads:position_watcher:throttle_ms", 200);
    public static final zzacj<Long> zzcqj = zzacj.zza(1, "gads:position_watcher:scroll_aware_throttle_ms", 33);
    public static final zzacj<Boolean> zzcqk = zzacj.zza(1, "gads:position_watcher:enable_scroll_aware_ads", (Boolean) false);
    public static final zzacj<Boolean> zzcql = zzacj.zza(1, "gads:position_watcher:send_scroll_data", (Boolean) false);
    public static final zzacj<Long> zzcqm = zzacj.zza(0, "gads:device_info_caching_expiry_ms:expiry", (long) Constants.MIN_TIME_BETWEEN_SESSIONS_MILLIS);
    private static final zzacj<Boolean> zzcqn = zzacj.zza(1, "gads:gen204_signals:enabled", (Boolean) false);
    public static final zzacj<Boolean> zzcqo = zzacj.zza(0, "gads:webview:error_reporting_enabled", (Boolean) false);
    private static final zzacj<Boolean> zzcqp = zzacj.zza(0, "gads:adid_reporting:enabled", (Boolean) false);
    private static final zzacj<Boolean> zzcqq = zzacj.zza(0, "gads:ad_settings_page_reporting:enabled", (Boolean) false);
    private static final zzacj<Boolean> zzcqr = zzacj.zza(0, "gads:adid_info_gmscore_upgrade_reporting:enabled", (Boolean) false);
    public static final zzacj<Long> zzcqs = zzacj.zza(1, "gads:rtb_signal_timeout_ms", 1000);
    public static final zzacj<Boolean> zzcqt = zzacj.zza(2, "rtb_enabled", (Boolean) false);
    public static final zzacj<Boolean> zzcqu = zzacj.zza(1, "gads:rtb_cld:enabled", (Boolean) false);
    private static final zzacj<Long> zzcqv = zzacj.zza(0, "gads:resolve_future:default_timeout_ms", 30000);
    private static final zzacj<Long> zzcqw = zzacj.zza(0, "gads:ad_loader:timeout_ms", 60000);
    public static final zzacj<Long> zzcqx = zzacj.zza(0, "gads:rendering:timeout_ms", 60000);
    public static final zzacj<Boolean> zzcqy = zzacj.zza(1, "gads:adapter_initialization:enabled", (Boolean) false);
    public static final zzacj<Long> zzcqz = zzacj.zza(1, "gads:adapter_initialization:timeout", 30);
    public static final zzacj<Long> zzcra = zzacj.zza(1, "gads:adapter_initialization:cld_timeout", 10);
    public static final zzacj<Boolean> zzcrb = zzacj.zza(0, "gads:adshield:enable_adshield_instrumentation", (Boolean) false);
    public static final zzacj<Boolean> zzcrc = zzacj.zza(1, "gads:gestures:errorlogging:enabled", (Boolean) false);
    public static final zzacj<Long> zzcrd = zzacj.zza(1, "gads:gestures:task_timeout", (long) AdaptiveTrackSelection.DEFAULT_MIN_TIME_BETWEEN_BUFFER_REEVALUTATION_MS);
    public static final zzacj<Boolean> zzcre = zzacj.zza(1, "gads:gestures:asig:enabled", (Boolean) false);
    public static final zzacj<Boolean> zzcrf = zzacj.zza(1, "gads:gestures:ans:enabled", (Boolean) false);
    public static final zzacj<Boolean> zzcrg = zzacj.zza(1, "gads:gestures:tos:enabled", (Boolean) false);
    public static final zzacj<Boolean> zzcrh = zzacj.zza(1, "gads:gestures:brt:enabled", (Boolean) true);
    public static final zzacj<Boolean> zzcri = zzacj.zza(1, "gads:signal:app_permissions:disabled", (Boolean) false);
    public static final zzacj<Boolean> zzcrj = zzacj.zza(1, "gads:gestures:inthex:enabled", (Boolean) false);
    public static final zzacj<Boolean> zzcrk = zzacj.zza(1, "gads:gestures:hpk:enabled", (Boolean) true);
    public static final zzacj<String> zzcrl = zzacj.zza(1, "gads:gestures:pk", "");
    public static final zzacj<Boolean> zzcrm = zzacj.zza(1, "gads:gestures:bs:enabled", (Boolean) true);
    public static final zzacj<Boolean> zzcrn = zzacj.zza(1, "gads:gestures:check_initialization_thread:enabled", (Boolean) false);
    public static final zzacj<Boolean> zzcro = zzacj.zza(1, "gads:gestures:get_query_in_non_ui_thread:enabled", (Boolean) true);
    public static final zzacj<Boolean> zzcrp = zzacj.zza(1, "gads:gestures:pds:enabled", (Boolean) false);
    public static final zzacj<Boolean> zzcrq = zzacj.zza(1, "gads:gestures:ns:enabled", (Boolean) false);
    public static final zzacj<Boolean> zzcrr = zzacj.zza(1, "gads:gestures:vdd:enabled", (Boolean) false);
    private static final zzacj<Boolean> zzcrs = zzacj.zza(0, "gads:adid_notification:first_party_check:enabled", (Boolean) true);
    private static final zzacj<Boolean> zzcrt = zzacj.zza(0, "gads:adid_track_reset_count:enabled", (Boolean) true);
    private static final zzacj<String> zzcru = zzacj.zzb(1, "gads:sdk_core_constants:experiment_id");
    public static final zzacj<String> zzcrv = zzacj.zza(1, "gads:sdk_core_constants:caps", "");
    public static final zzacj<Long> zzcrw = zzacj.zza(0, "gads:js_flags:update_interval", TimeUnit.HOURS.toMillis(12));
    public static final zzacj<Boolean> zzcrx = zzacj.zza(0, "gads:js_flags:mf", (Boolean) false);
    private static final zzacj<Boolean> zzcry = zzacj.zza(1, "gads:js_flags:disable_phenotype", (Boolean) false);
    private static final zzacj<Boolean> zzcrz = zzacj.zza(0, "gads:custom_render:ping_on_ad_rendered", (Boolean) false);
    public static final zzacj<String> zzcsa = zzacj.zza(1, "gads:native:engine_url_with_protocol", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/native_ads.html");
    private static final zzacj<String> zzcsb = zzacj.zza(0, "gads:native:engine_js_url_with_protocol", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/native_ads.js");
    private static final zzacj<String> zzcsc = zzacj.zza(1, "gads:native:video_url", "//imasdk.googleapis.com/admob/sdkloader/native_video.html");
    public static final zzacj<String> zzcsd = zzacj.zza(1, "gads:native:video_url_with_protocol", "https://imasdk.googleapis.com/admob/sdkloader/native_video.html");
    public static final zzacj<Integer> zzcse = zzacj.zza(1, "gads:native_video_load_timeout", 10);
    private static final zzacj<Integer> zzcsf = zzacj.zza(1, "gads:omid:native_webview_load_timeout", 2000);
    public static final zzacj<Boolean> zzcsg = zzacj.zza(1, "gads:enable_native_media_aspect_ratio", (Boolean) true);
    public static final zzacj<String> zzcsh = zzacj.zza(1, "gads:ad_choices_content_description", "Ad Choices Icon");
    private static final zzacj<Boolean> zzcsi = zzacj.zza(1, "gads:enable_store_active_view_state", (Boolean) false);
    public static final zzacj<Boolean> zzcsj = zzacj.zza(1, "gads:enable_singleton_broadcast_receiver", (Boolean) false);
    public static final zzacj<Boolean> zzcsk = zzacj.zza(1, "gads:native:media_view_match_parent:enabled", (Boolean) false);
    public static final zzacj<Boolean> zzcsl = zzacj.zza(1, "gads:native:count_impression_for_assets", (Boolean) false);
    private static final zzacj<Boolean> zzcsm = zzacj.zza(1, "gads:instream_ad:enabled", (Boolean) true);
    public static final zzacj<Boolean> zzcsn = zzacj.zza(1, "gads:fluid_ad:use_wrap_content_height", (Boolean) false);
    private static final zzacj<Boolean> zzcso = zzacj.zza(1, "gads:auto_location_for_coarse_permission", (Boolean) false);
    private static final zzacj<String> zzcsp = zzacj.zzc(1, "gads:auto_location_for_coarse_permission:experiment_id");
    public static final zzacj<Long> zzcsq = zzacj.zza(1, "gads:auto_location_timeout", (long) AdaptiveTrackSelection.DEFAULT_MIN_TIME_BETWEEN_BUFFER_REEVALUTATION_MS);
    private static final zzacj<String> zzcsr = zzacj.zzc(1, "gads:auto_location_timeout:experiment_id");
    private static final zzacj<Long> zzcss = zzacj.zza(1, "gads:auto_location_interval", -1);
    private static final zzacj<String> zzcst = zzacj.zzc(1, "gads:auto_location_interval:experiment_id");
    private static final zzacj<Boolean> zzcsu = zzacj.zza(0, "gads:auto_location_interval:without_thread", (Boolean) true);
    public static final zzacj<Boolean> zzcsv = zzacj.zza(1, "gads:fetch_app_settings_using_cld:enabled", (Boolean) false);
    private static final zzacj<String> zzcsw = zzacj.zzb(1, "gads:fetch_app_settings_using_cld:enabled:experiment_id");
    public static final zzacj<Boolean> zzcsx = zzacj.zza(1, "gads:use_manifest_appid_cld:enabled", (Boolean) false);
    public static final zzacj<Long> zzcsy = zzacj.zza(1, "gads:fetch_app_settings_using_cld:refresh_interval_ms", 7200000);
    private static final zzacj<String> zzcsz = zzacj.zzb(0, "gads:afs:csa:experiment_id");
    private static final zzacj<String> zzcta = zzacj.zza(0, "gads:afs:csa_webview_gmsg_ad_failed", "gmsg://noAdLoaded");
    private static final zzacj<String> zzctb = zzacj.zza(0, "gads:afs:csa_webview_gmsg_script_load_failed", "gmsg://scriptLoadFailed");
    private static final zzacj<String> zzctc = zzacj.zza(0, "gads:afs:csa_webview_gmsg_ad_loaded", "gmsg://adResized");
    private static final zzacj<String> zzctd = zzacj.zza(0, "gads:afs:csa_webview_static_file_path", "/afs/ads/i/webview.html");
    private static final zzacj<String> zzcte = zzacj.zza(0, "gads:afs:csa_webview_custom_domain_param_key", "csa_customDomain");
    private static final zzacj<Long> zzctf = zzacj.zza(0, "gads:afs:csa_webview_adshield_timeout_ms", 1000);
    public static final zzacj<Long> zzctg = zzacj.zza(1, "gads:parental_controls:timeout", (long) AdaptiveTrackSelection.DEFAULT_MIN_TIME_BETWEEN_BUFFER_REEVALUTATION_MS);
    private static final zzacj<String> zzcth = zzacj.zza(0, "gads:safe_browsing:api_key", "AIzaSyDRKQ9d6kfsoZT2lUnZcZnBYvH69HExNPE");
    private static final zzacj<Long> zzcti = zzacj.zza(0, "gads:safe_browsing:safety_net:delay_ms", (long) AdaptiveTrackSelection.DEFAULT_MIN_TIME_BETWEEN_BUFFER_REEVALUTATION_MS);
    public static final zzacj<Boolean> zzctj = zzacj.zza(0, "gads:safe_browsing:debug", (Boolean) false);
    private static final zzacj<Integer> zzctk = zzacj.zza(1, "gads:cache:ad_request_timeout_millis", (int) ItemTouchHelper.Callback.DEFAULT_SWIPE_ANIMATION_DURATION);
    private static final zzacj<Integer> zzctl = zzacj.zza(1, "gads:cache:max_concurrent_downloads", 10);
    private static final zzacj<Long> zzctm = zzacj.zza(1, "gads:cache:javascript_timeout_millis", (long) DefaultRenderersFactory.DEFAULT_ALLOWED_VIDEO_JOINING_TIME_MS);
    public static final zzacj<Boolean> zzctn = zzacj.zza(1, "gads:cache:bind_on_foreground", (Boolean) false);
    public static final zzacj<Boolean> zzcto = zzacj.zza(1, "gads:cache:bind_on_init", (Boolean) false);
    public static final zzacj<Boolean> zzctp = zzacj.zza(1, "gads:cache:bind_on_request", (Boolean) false);
    public static final zzacj<Long> zzctq = zzacj.zza(1, "gads:cache:bind_on_request_keep_alive", TimeUnit.SECONDS.toMillis(30));
    public static final zzacj<Boolean> zzctr = zzacj.zza(1, "gads:cache:use_cache_data_source", (Boolean) false);
    public static final zzacj<Boolean> zzcts = zzacj.zza(1, "gads:cache:connection_per_read", (Boolean) false);
    public static final zzacj<Long> zzctt = zzacj.zza(1, "gads:cache:connection_timeout", (long) DefaultRenderersFactory.DEFAULT_ALLOWED_VIDEO_JOINING_TIME_MS);
    public static final zzacj<Long> zzctu = zzacj.zza(1, "gads:cache:read_only_connection_timeout", (long) DefaultRenderersFactory.DEFAULT_ALLOWED_VIDEO_JOINING_TIME_MS);
    public static final zzacj<Boolean> zzctv = zzacj.zza(1, "gads:http_assets_cache:enabled", (Boolean) false);
    public static final zzacj<String> zzctw = zzacj.zza(1, "gads:http_assets_cache:regex", "(?i)https:\\/\\/(tpc\\.googlesyndication\\.com\\/(.*)|lh\\d+\\.googleusercontent\\.com\\/(.*))");
    public static final zzacj<Integer> zzctx = zzacj.zza(1, "gads:http_assets_cache:time_out", 100);
    public static final zzacj<Boolean> zzcty = zzacj.zza(1, "gads:chrome_custom_tabs_browser:enabled", (Boolean) false);
    public static final zzacj<Boolean> zzctz = zzacj.zza(1, "gads:chrome_custom_tabs:disabled", (Boolean) false);
    public static final zzacj<Long> zzcua = zzacj.zza(1, "gads:debug_hold_gesture:time_millis", (long) AdaptiveTrackSelection.DEFAULT_MIN_TIME_BETWEEN_BUFFER_REEVALUTATION_MS);
    public static final zzacj<String> zzcub = zzacj.zza(1, "gads:drx_debug:debug_device_linking_url", "https://www.google.com/dfp/linkDevice");
    public static final zzacj<String> zzcuc = zzacj.zza(1, "gads:drx_debug:in_app_preview_status_url", "https://www.google.com/dfp/inAppPreview");
    public static final zzacj<String> zzcud = zzacj.zza(1, "gads:drx_debug:debug_signal_status_url", "https://www.google.com/dfp/debugSignals");
    public static final zzacj<String> zzcue = zzacj.zza(1, "gads:drx_debug:send_debug_data_url", "https://www.google.com/dfp/sendDebugData");
    public static final zzacj<Integer> zzcuf = zzacj.zza(1, "gads:drx_debug:timeout_ms", 5000);
    public static final zzacj<Integer> zzcug = zzacj.zza(1, "gad:pixel_dp_comparision_multiplier", 1);
    public static final zzacj<Boolean> zzcuh = zzacj.zza(1, "gad:interstitial_for_multi_window", (Boolean) false);
    public static final zzacj<Boolean> zzcui = zzacj.zza(1, "gad:interstitial_ad_stay_active_in_multi_window", (Boolean) false);
    public static final zzacj<Boolean> zzcuj = zzacj.zza(1, "gad:interstitial_multi_window_method", (Boolean) false);
    public static final zzacj<Integer> zzcuk = zzacj.zza(1, "gad:interstitial:close_button_padding_dip", 0);
    public static final zzacj<Boolean> zzcul = zzacj.zza(1, "gads:clearcut_logging:enabled", (Boolean) false);
    public static final zzacj<Boolean> zzcum = zzacj.zza(1, "gads:clearcut_logging:write_to_file", (Boolean) false);
    private static final zzacj<Boolean> zzcun = zzacj.zza(0, "gad:force_local_ad_request_service:enabled", (Boolean) false);
    public static final zzacj<Boolean> zzcuo = zzacj.zza(1, "gad:publisher_testing:force_local_request:enabled", (Boolean) true);
    public static final zzacj<String> zzcup = zzacj.zza(1, "gad:publisher_testing:force_local_request:enabled_list", "");
    public static final zzacj<String> zzcuq = zzacj.zza(1, "gad:publisher_testing:force_local_request:disabled_list", "");
    public static final zzacj<Boolean> zzcur = zzacj.zza(0, "gad:force_dynamite_loading_enabled", (Boolean) false);
    private static final zzacj<String> zzcus = zzacj.zzb(0, "gad:dynamite_module:experiment_id");
    public static final zzacj<Integer> zzcut = zzacj.zza(1, "gad:http_redirect_max_count:times", 8);
    public static final zzacj<Boolean> zzcuu = zzacj.zza(1, "gads:omid:enabled", (Boolean) false);
    public static final zzacj<Integer> zzcuv = zzacj.zza(1, "gads:omid:destroy_webview_delay", 1000);
    public static final zzacj<Boolean> zzcuw = zzacj.zza(0, "gads:nonagon:red_button", (Boolean) false);
    private static final zzacj<Boolean> zzcux = zzacj.zza(1, "gads:nonagon:banner:enabled", (Boolean) false);
    private static final zzacj<String> zzcuy = zzacj.zza(1, "gads:nonagon:banner:ad_unit_exclusions", "(?!)");
    private static final zzacj<Boolean> zzcuz = zzacj.zza(1, "gads:nonagon:interstitial:enabled", (Boolean) false);
    private static final zzacj<String> zzcva = zzacj.zza(1, "gads:nonagon:interstitial:ad_unit_exclusions", "(?!)");
    private static final zzacj<Boolean> zzcvb = zzacj.zza(1, "gads:nonagon:rewardedvideo:enabled", (Boolean) false);
    public static final zzacj<Boolean> zzcvc = zzacj.zza(1, "gads:nonagon:mobile_ads_setting_manager:enabled", (Boolean) false);
    public static final zzacj<String> zzcvd = zzacj.zza(1, "gads:nonagon:rewardedvideo:ad_unit_exclusions", "(?!)");
    private static final zzacj<Boolean> zzcve = zzacj.zza(1, "gads:nonagon:nativead:enabled", (Boolean) false);
    private static final zzacj<String> zzcvf = zzacj.zza(1, "gads:nonagon:nativead:app_name", "(?!)");
    public static final zzacj<Boolean> zzcvg = zzacj.zza(1, "gads:nonagon:banner:check_dp_size", (Boolean) true);
    public static final zzacj<Boolean> zzcvh = zzacj.zza(1, "gads:nonagon:rewarded:load_multiple_ads", (Boolean) true);
    private static final zzacj<Boolean> zzcvi = zzacj.zza(1, "gads:nonagon:return_last_error_code", (Boolean) false);
    public static final zzacj<Boolean> zzcvj = zzacj.zza(1, "gads:nonagon:return_no_fill_error_code", (Boolean) false);
    public static final zzacj<Boolean> zzcvk = zzacj.zza(1, "gads:nonagon:continue_on_no_fill", (Boolean) false);
    private static final zzacj<Boolean> zzcvl = zzacj.zza(1, "gads:nonagon:open_not_loaded_interstitial", (Boolean) true);
    public static final zzacj<Boolean> zzcvm = zzacj.zza(1, "gads:nonagon:separate_timeout:enabled", (Boolean) true);
    public static final zzacj<Integer> zzcvn = zzacj.zza(1, "gads:nonagon:request_timeout:seconds", 60);
    public static final zzacj<Boolean> zzcvo = zzacj.zza(0, "gads:nonagon:limit_ad_request_connection", (Boolean) true);
    public static final zzacj<Boolean> zzcvp = zzacj.zza(1, "gads:nonagon:javascript_ad_request:enabled", (Boolean) false);
    public static final zzacj<Boolean> zzcvq = zzacj.zza(1, "gads:nonagon:banner_recursive_renderer", (Boolean) false);
    private static final zzacj<Boolean> zzcvr = zzacj.zza(1, "gads:nonagon:service:enabled", (Boolean) true);
    public static final zzacj<Boolean> zzcvs = zzacj.zza(1, "gads:nonagon:active_view_gmsg_background_thread:enabled", (Boolean) true);
    public static final zzacj<Boolean> zzcvt = zzacj.zza(1, "gads:signals:ad_id_info:enabled", (Boolean) false);
    public static final zzacj<Boolean> zzcvu = zzacj.zza(1, "gads:signals:app_index:enabled", (Boolean) false);
    public static final zzacj<Boolean> zzcvv = zzacj.zza(1, "gads:signals:cache:enabled", (Boolean) false);
    public static final zzacj<Boolean> zzcvw = zzacj.zza(1, "gads:signals:doritos:enabled", (Boolean) false);
    public static final zzacj<Boolean> zzcvx = zzacj.zza(1, "gads:signals:doritos:v1:enabled", (Boolean) false);
    private static final zzacj<Boolean> zzcvy = zzacj.zza(1, "gads:signals:doritos:v2:immediate:enabled", (Boolean) false);
    public static final zzacj<Boolean> zzcvz = zzacj.zza(1, "gads:signals:location:enabled", (Boolean) false);
    private static final zzacj<Boolean> zzcwa = zzacj.zza(1, "gads:signals:network_prediction:enabled", (Boolean) false);
    public static final zzacj<Boolean> zzcwb = zzacj.zza(1, "gads:signals:parental_control:enabled", (Boolean) false);
    public static final zzacj<Boolean> zzcwc = zzacj.zza(1, "gads:signals:video_decoder:enabled", (Boolean) false);
    public static final zzacj<Boolean> zzcwd = zzacj.zza(1, "gads:signals:signals_on_service:enabled", (Boolean) false);
    public static final zzacj<Long> zzcwe = zzacj.zza(1, "gads:mobius_linking:sdk_side_cooldown_time_threshold:ms", (long) DateUtils.MILLIS_PER_HOUR);
    public static final zzacj<String> zzcwf = zzacj.zza(0, "gads:public_beta:traffic_multiplier", "1.0");
    public static final zzacj<Integer> zzcwg = zzacj.zza(1, "gads:adoverlay:b68684796:targeting_sdk:lower_bound", 27);
    public static final zzacj<Integer> zzcwh = zzacj.zza(1, "gads:adoverlay:b68684796:targeting_sdk:upper_bound", (int) RoomDatabase.MAX_BIND_PARAMETER_CNT);
    public static final zzacj<Integer> zzcwi = zzacj.zza(1, "gads:adoverlay:b68684796:sdk_int:lower_bound", 26);
    public static final zzacj<Integer> zzcwj = zzacj.zza(1, "gads:adoverlay:b68684796:sdk_int:upper_bound", 27);
    private static final zzacj<Boolean> zzcwk = zzacj.zza(0, "gads:rewarded_sku:enabled", (Boolean) true);
    private static final zzacj<Boolean> zzcwl = zzacj.zza(0, "gads:rewarded_sku:override_test:enabled", (Boolean) false);
    public static final zzacj<Boolean> zzcwm = zzacj.zza(1, "gads:consent:shared_preference_reading:enabled", (Boolean) true);
    public static final zzacj<Boolean> zzcwn = zzacj.zza(1, "gads:consent:iab_consent_info:enabled", (Boolean) true);
    public static final zzacj<Boolean> zzcwo = zzacj.zza(1, "gads:nativeads:image:sample:enabled", (Boolean) true);
    public static final zzacj<Integer> zzcwp = zzacj.zza(1, "gads:nativeads:image:sample:pixels", 1048576);
    public static final zzacj<Boolean> zzcwq = zzacj.zza(1, "gads:nativeads:overlay_webview:onclick", (Boolean) false);
    public static final zzacj<Integer> zzcwr = zzacj.zza(0, "gads:dynamite_load:fail:sample_rate", 10000);
    private static final zzacj<Boolean> zzcws = zzacj.zza(0, "gads:service:webview:enable_directory_suffix", (Boolean) true);
    public static final zzacj<Boolean> zzcwt = zzacj.zza(1, "gads:offline_signaling:enabled", (Boolean) false);
    public static final zzacj<Integer> zzcwu = zzacj.zza(1, "gads:offline_signaling:log_maximum", 100);
    public static final zzacj<Boolean> zzcwv = zzacj.zza(0, "gads:uri_query_to_map_rewrite:enabled", (Boolean) false);
    public static final zzacj<Boolean> zzcww = zzacj.zza(1, "gads:nativeads:template_signal:enabled", (Boolean) true);
    public static final zzacj<Boolean> zzcwx = zzacj.zza(1, "gads:nativeads:media_content_aspect_ratio:enabled", (Boolean) true);
    private static byte[] zzcwy;

    public static void initialize(Context context) {
        zzazl.zza(context, new zzacv(context));
        int intValue = ((Integer) zzyt.zzpe().zzd(zzcqd)).intValue();
        if (intValue > 0 && zzcwy == null) {
            zzcwy = new byte[intValue];
        }
    }

    public static void zza(Context context, int i, JSONObject jSONObject) {
        zzyt.zzpc();
        SharedPreferences.Editor edit = context.getSharedPreferences("google_ads_flags", 0).edit();
        zzyt.zzpd().zza(edit, 1, jSONObject);
        zzyt.zzpc();
        edit.commit();
    }

    public static List<String> zzqn() {
        return zzyt.zzpd().zzqn();
    }

    public static List<String> zzqo() {
        return zzyt.zzpd().zzqo();
    }
}
